/**Store reused variables here */
const counties: any = [
  'Baringo',
  'Bomet',
  'Bungoma',
  'Busia',
  'Elgeyo-Marakwet',
  'Embu',
  'Garissa',
  'HomaBay',
  'Isiolo',
  'Kajiado',
  'Kakamega',
  'Kericho',
  'Kiambu',
  'Kilifi',
  'Kirinyaga',
  'Kisii',
  'Kisumu',
  'Kitui',
  'Kwale',
  'Laikipia',
  'Lamu',
  'Machakos',
  'Makueni',
  'Mandera',
  'Marsabit',
  'Meru',
  'Migori',
  'Mombasa',
  "Murang'a",
  'Nairobi',
  'Nakuru',
  'Nandi',
  'Narok',
  'Nyamira',
  'Nyandarua',
  'Nyeri',
  'Samburu',
  'Siaya',
  'Taita-Taveta',
  'TanaRiver',
  'Tharaka-Nithi',
  'TransNzoia',
  'Turkana',
  'UasinGishu',
  'Vihiga',
  'Wajir',
  'WestPokot',
];
const genders = ['male', 'female', 'other'];
const roles = ['user', 'supervisor', 'manager'];

export { counties, genders, roles };
